apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-producer-config
data:
  RABBITMQ_HOST: "34.66.104.2"  
  RABBITMQ_PORT: "30764"        
  RABBITMQ_VHOST: "/"
  QUEUE_NAME: "messages"
  EXCHANGE: ""
  ROUTING_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-producer-secret
type: Opaque
data:
  RABBITMQ_USERNAME: "" 
  RABBITMQ_PASSWORD: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-producer
  labels:
    app: rabbitmq-producer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: rabbitmq-producer
  template:
    metadata:
      labels:
        app: rabbitmq-producer
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - gke-swarit-cluster-ng-4-8-78dd99fc-0ljk
      containers:
      - name: rabbitmq-producer
        image: sprectza/stress-rmq-producer:v1
        imagePullPolicy: IfNotPresent
        command:
        - /app/rabbitmq-producer
        args:
        - "-producers=1000"                     
        - "-mps=1"                              
        - "-host=$(RABBITMQ_HOST)"              
        - "-port=$(RABBITMQ_PORT)"              
        - "-username=$(RABBITMQ_USERNAME)"      
        - "-password=$(RABBITMQ_PASSWORD)"      
        - "-queue=$(QUEUE_NAME)"                
        - "-routing-key=$(ROUTING_KEY)"         
        - "-duration=0"                         
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-producer-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-producer-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_VHOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-producer-config
              key: RABBITMQ_VHOST
        - name: QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-producer-config
              key: QUEUE_NAME
        - name: EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-producer-config
              key: EXCHANGE
        - name: ROUTING_KEY
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-producer-config
              key: ROUTING_KEY
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-producer-secret
              key: RABBITMQ_USERNAME
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-producer-secret
              key: RABBITMQ_PASSWORD
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          exec:
            command:
            - pgrep
            - "rabbitmq-producer"
          initialDelaySeconds: 5
          periodSeconds: 10



















